export interface Course {
  id: string;
  name: string;
  eco: string;
  color: 'white' | 'black';
  lines: number;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  description: string;
  popularity: number;
  moves: string;
}

export const courses: Course[] = [
  {
    id: 'italian-game',
    name: 'Italian Game',
    eco: 'C50',
    color: 'white',
    lines: 40,
    difficulty: 'beginner',
    description: " An OG opening created in the late 15th and early 16th centuries. I like pizza",
    popularity: 89,
    moves: '1.e4 e5 2.Nf3 Nc6 3.Bc4',
  },
  {
    id: 'sicilian-dragon',
    name: 'Sicilian Dragon',
    eco: 'B70',
    color: 'black',
    lines: 40,
    difficulty: 'advanced',
    description: "Simple but great opening. Make your opponent regret 1.e4.",
    popularity: 72,
    moves: '1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 g6',
  },
  {
    id: 'london-system',
    name: 'London System',
    eco: 'D02',
    color: 'white',
    lines: 40,
    difficulty: 'beginner',
    description: "Boring? Maybe. Reliable? Absolutely. Zero theory, maximum suffering for Black.",
    popularity: 94,
    moves: '1.d4 d5 2.Bf4',
  },
  {
    id: 'caro-kann',
    name: 'Caro-Kann Defense',
    eco: 'B10',
    color: 'black',
    lines: 40,
    difficulty: 'intermediate',
    description: "Solid as a rock. Very Reliable, and mostly, GothamChess glazes it.",
    popularity: 81,
    moves: '1.e4 c6',
  },
  {
    id: 'kings-indian',
    name: "King's Indian Defense",
    eco: 'E60',
    color: 'black',
    lines: 40,
    difficulty: 'advanced',
    description: "Let them think they're winning. Then unleash Kingside armageddon.",
    popularity: 68,
    moves: '1.d4 Nf6 2.c4 g6',
  },
  {
    id: 'queens-gambit',
    name: "Queen's Gambit",
    eco: 'D06',
    color: 'white',
    lines: 40,
    difficulty: 'intermediate',
    description: "The Netflix special. Offer that pawn. They'll never take it anyway.",
    popularity: 88,
    moves: '1.d4 d5 2.c4',
  },
  {
    id: 'french-defense',
    name: 'French Defense',
    eco: 'C00',
    color: 'black',
    lines: 40,
    difficulty: 'intermediate',
    description: "Build a pawn fortress. Laugh at their e5 pawn. Très magnifique.",
    popularity: 75,
    moves: '1.e4 e6',
  },
  {
    id: 'ruy-lopez',
    name: 'Ruy Lopez',
    eco: 'C60',
    color: 'white',
    lines: 40,
    difficulty: 'intermediate',
    description: "500 years of torture. Pin that knight. Collect your rating points.",
    popularity: 85,
    moves: '1.e4 e5 2.Nf3 Nc6 3.Bb5',
  },
  {
    id: 'scandinavian',
    name: 'Scandinavian Defense',
    eco: 'B01',
    color: 'black',
    lines: 40,
    difficulty: 'beginner',
    description: "Take that pawn. Retreat the queen. Confuse literally everyone.",
    popularity: 63,
    moves: '1.e4 d5',
  },
  {
    id: 'grunfeld',
    name: 'Grünfeld Defense',
    eco: 'D80',
    color: 'black',
    lines: 40,
    difficulty: 'advanced',
    description: "Give them the center. Then blow it up. Controlled chaos.",
    popularity: 58,
    moves: '1.d4 Nf6 2.c4 g6 3.Nc3 d5',
  },
  {
    id: 'vienna-game',
    name: 'Vienna Game',
    eco: 'C25',
    color: 'white',
    lines: 40,
    difficulty: 'beginner',
    description: "Italian Game's cooler cousin. Very powerful Gambit.",
    popularity: 52,
    moves: '1.e4 e5 2.Nc3',
  },
  {
    id: 'dutch-defense',
    name: 'Dutch Defense',
    eco: 'A80',
    color: 'black',
    lines: 40,
    difficulty: 'intermediate',
    description: "f5 on move 1 against 1.d4. Your opponents won't expect that.",
    popularity: 45,
    moves: '1.d4 f5',
  },
  {
    id: 'stafford-gambit',
    name: 'Stafford Gambit',
    eco: 'C42',
    color: 'black',
    lines: 40,
    difficulty: 'intermediate',
    description: "Sacrifice a pawn, win in 8 moves. The ultimate blitz weapon.",
    popularity: 78,
    moves: '1.e4 e5 2.Nf3 Nf6 3.Nxe5 Nc6',
  },
  {
    id: 'sicilian-najdorf',
    name: 'Sicilian Najdorf',
    eco: 'B90',
    color: 'black',
    lines: 40,
    difficulty: 'advanced',
    description: "Fischer's choice. The sharpest, most theoretical opening in chess.",
    popularity: 91,
    moves: '1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 a6',
  },
  {
    id: 'sicilian-sveshnikov',
    name: 'Sicilian Sveshnikov',
    eco: 'B33',
    color: 'black',
    lines: 40,
    difficulty: 'advanced',
    description: "Accept a hole on d5, destroy on the kingside. Aggressive and dynamic.",
    popularity: 76,
    moves: '1.e4 c5 2.Nf3 Nc6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 e5',
  },
  {
    id: 'sicilian-kan',
    name: 'Sicilian Kan',
    eco: 'B42',
    color: 'black',
    lines: 40,
    difficulty: 'intermediate',
    description: "Flexible and solid. Keep your options open while Black develops smoothly.",
    popularity: 65,
    moves: '1.e4 c5 2.Nf3 e6 3.d4 cxd4 4.Nxd4 a6',
  },
  {
    id: 'sicilian-scheveningen',
    name: 'Sicilian Scheveningen',
    eco: 'B80',
    color: 'black',
    lines: 40,
    difficulty: 'advanced',
    description: "The small center that fights back. Classic Sicilian structure.",
    popularity: 70,
    moves: '1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 e6',
  },
  {
    id: 'trompowsky',
    name: 'Trompowsky Attack',
    eco: 'A45',
    color: 'white',
    lines: 1,
    difficulty: 'intermediate',
    description: "GothamChess likes this lots too.",
    popularity: 60,
    moves: '1.d4 Nf6 2.Bg5',
  },
  {
    id: 'catalan',
    name: 'Catalan Opening',
    eco: 'E00',
    color: 'white',
    lines: 1,
    difficulty: 'advanced',
    description: "Fianchetto the bishop. Its similar to the queen's gambit and GMs love it.",
    popularity: 82,
    moves: '1.d4 Nf6 2.c4 e6 3.g3',
  },
  {
    id: 'scotch-game',
    name: 'Scotch Game',
    eco: 'C45',
    color: 'white',
    lines: 1,
    difficulty: 'intermediate',
    description: "Open the center early. Kasparov's surprise weapon.",
    popularity: 74,
    moves: '1.e4 e5 2.Nf3 Nc6 3.d4',
  },
  {
    id: 'nimzo-indian',
    name: 'Nimzo-Indian Defense',
    eco: 'E20',
    color: 'black',
    lines: 1,
    difficulty: 'advanced',
    description: "Pin the knight, control e4. The most respected defense against 1.d4.",
    popularity: 86,
    moves: '1.d4 Nf6 2.c4 e6 3.Nc3 Bb4',
  },
  {
    id: 'elephant-gambit',
    name: 'Elephant Gambit',
    eco: 'C40',
    color: 'black',
    lines: 1,
    difficulty: 'intermediate',
    description: "This has a very high winrate for some reason.",
    popularity: 35,
    moves: '1.e4 e5 2.Nf3 d5',
  },
  {
    id: 'traxler-counterattack',
    name: 'Traxler Counterattack',
    eco: 'C57',
    color: 'black',
    lines: 1,
    difficulty: 'advanced',
    description: "It's used to counter the common Fried Liver attack.",
    popularity: 55,
    moves: '1.e4 e5 2.Nf3 Nc6 3.Bc4 Nf6 4.Ng5 Bc5',
  },
  {
    id: 'rousseau-gambit',
    name: 'Rousseau Gambit',
    eco: 'C50',
    color: 'black',
    lines: 1,
    difficulty: 'intermediate',
    description: "Sacrifice a pawn for rapid development. A reverse vienna gambit.",
    popularity: 30,
    moves: '1.e4 e5 2.Nf3 Nc6 3.Bc4 f5',
  },
  {
    id: 'englund-gambit',
    name: 'Englund Gambit',
    eco: 'A40',
    color: 'black',
    lines: 1,
    difficulty: 'beginner',
    description: "1...e5 against d4.Very annoying for the opponent.",
    popularity: 40,
    moves: '1.d4 e5',
  },
  {
    id: 'bishops-opening',
    name: "Bishop's Opening",
    eco: 'C23',
    color: 'white',
    lines: 1,
    difficulty: 'beginner',
    description: "Develop the bishop first. Flexible, solid, and underestimated.",
    popularity: 50,
    moves: '1.e4 e5 2.Bc4',
  },
  {
    id: 'alekhine-defense',
    name: 'Alien Gambit',
    eco: 'B02',
    color: 'white',
    lines: 1,
    difficulty: 'intermediate',
    description: "Fun to play, but stockfish won't like it",
    popularity: 55,
    moves: '1.e4 Nf6',
  },
  {
    id: 'danish-gambit',
    name: 'Danish Gambit',
    eco: 'C21',
    color: 'white',
    lines: 1,
    difficulty: 'intermediate',
    description: "This was just made to make you feel like Tal and farm brilliant moves.",
    popularity: 48,
    moves: '1.e4 e5 2.d4 exd4 3.c3',
  },
];

export const getDifficultyColor = (difficulty: Course['difficulty']) => {
  switch (difficulty) {
    case 'beginner':
      return 'text-primary';
    case 'intermediate':
      return 'text-accent';
    case 'advanced':
      return 'text-destructive';
  }
};

export const getDifficultyLabel = (difficulty: Course['difficulty']) => {
  switch (difficulty) {
    case 'beginner':
      return 'Beginner';
    case 'intermediate':
      return 'Intermediate';
    case 'advanced':
      return 'Advanced';
  }
};
